name: Doxygen Build and Release on ubuntu-20.04

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Optional: Git ref to build (branch, tag, or SHA)"
        required: false
        default: ""

permissions:
  contents: write

jobs:
  # Job to fetch the latest Doxygen release tag
  get-latest-tag:
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.get_tag.outputs.latest_tag }}
      release_ref: ${{ steps.get_ref.outputs.ref }}
      commit_sha: ${{ steps.get_sha.outputs.commit_sha }}
    steps:
      - name: Get latest release tag
        id: get_tag
        run: |
          # Fetch the latest release tag from Doxygen GitHub repository
          LATEST_TAG=$(curl -s "https://api.github.com/repos/doxygen/doxygen/releases/latest" | jq -r '.tag_name')
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT
          echo "Using latest tag: $LATEST_TAG"

      - name: Determine build ref
        id: get_ref
        run: |
          # Use custom ref if provided, otherwise use latest tag
          if [ -n "${{ github.event.inputs.ref }}" ]; then
            echo "Using custom ref: ${{ github.event.inputs.ref }}"
            echo "ref=${{ github.event.inputs.ref }}" >> $GITHUB_OUTPUT
          else
            echo "Using latest tag as ref: ${{ steps.get_tag.outputs.latest_tag }}"
            echo "ref=${{ steps.get_tag.outputs.latest_tag }}" >> $GITHUB_OUTPUT
          fi

      - name: Get commit SHA for ref
        id: get_sha
        uses: actions/github-script@v7
        with:
          script: |
            const ref = '${{ steps.get_ref.outputs.ref }}';
            try {
              const response = await github.rest.repos.getCommit({
                owner: 'doxygen',
                repo: 'doxygen',
                ref: ref
              });
              return response.data.sha;
            } catch (error) {
              console.error(`Error fetching commit for ref '${ref}': ${error}`);
              throw error;
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    permissions:
      contents: write
    needs: get-latest-tag
    name: ${{ matrix.config.name }}
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04  # Use Ubuntu 20.04 container
      options: --user root
    strategy:
      fail-fast: false
      matrix:
        config:
          # GCC build configuration for Ubuntu 20.04
          - name: "Ubuntu 20.04 GCC Release x86_64"
            os: ubuntu-20.04
            platform: amd64
            build_type: "Release"
            cc: "gcc"
            cxx: "g++"
            build_gen: "Ninja"
            cmake_extra_opts: >-
              "-Duse_libclang=YES"
              "-Dstatic_libclang=YES"
              "-Dbuild_search=YES"
              "-Dbuild_app=YES"
              "-Dbuild_parse=YES"
              "-Dbuild_doc=YES"
              "-Dbuild_wizard=YES"
              "-DCMAKE_FIND_LIBRARY_SUFFIXES=\".a\""
              "-DBUILD_SHARED_LIBS=OFF"
              "-DCMAKE_EXE_LINKER_FLAGS=-static-libgcc -static-libstdc++"
              "-DCMAKE_SHARED_LINKER_FLAGS=-static-libgcc -static-libstdc++"

          # Clang build configuration for Ubuntu 20.04 using clang-9
          - name: "Ubuntu 20.04 Clang Release x86_64"
            os: ubuntu-20.04
            platform: amd64
            build_type: "Release"
            cc: "clang"
            cxx: "clang++"
            build_gen: "Ninja"
            cmake_extra_opts: >-
              "-Duse_libclang=YES"
              "-Dstatic_libclang=YES"
              "-Duse_libc++=NO"
              "-Dbuild_search=YES"
              "-Dbuild_app=YES"
              "-Dbuild_parse=YES"
              "-Dbuild_doc=YES"
              "-Dbuild_wizard=YES"
              "-DCMAKE_FIND_LIBRARY_SUFFIXES=\".a\""
              "-DBUILD_SHARED_LIBS=OFF"
              "-DCMAKE_EXE_LINKER_FLAGS=-static-libgcc -static-libstdc++"
              "-DCMAKE_SHARED_LINKER_FLAGS=-static-libgcc -static-libstdc++"

    steps:
      - name: Install core build dependencies
        run: |
          # Update package lists
          apt-get update

          # Install absolutely essential dependencies first
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
            ca-certificates \
            software-properties-common \
            apt-transport-https \
            gnupg \
            wget \
            file

          # Add required repositories
          add-apt-repository -y ppa:git-core/ppa

          # Install Kitware signing key properly
          wget -qO- https://apt.kitware.com/keys/kitware-archive-latest.asc | \
            gpg --dearmor -o /usr/share/keyrings/kitware-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ focal main" | \
            tee /etc/apt/sources.list.d/kitware.list >/dev/null

          # Update again with new repositories
          apt-get update

          # Install all build dependencies
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
            ninja-build \
            libz-dev \
            libc-ares-dev \
            p7zip-full \
            curl \
            jq \
            sudo \
            git \
            cmake \
            python3.8 \
            python3.8-dev \
            build-essential \
            binutils \
            gcc-9 \
            g++-9

      - name: Checkout doxygen
        uses: actions/checkout@v4
        with:
          repository: doxygen/doxygen
          ref: ${{ needs.get-latest-tag.outputs.release_ref }}
          fetch-depth: 0


      - name: Install clang-9 (Clang builds only)
        run: |
          # Completely remove any existing LLVM/Clang installations
          apt-get remove --purge -y '^llvm-.*' '^clang-.*' '^libclang-.*' '^libllvm.*' || true
          apt-get autoremove -y
          apt-get clean
          echo "All existing LLVM/Clang versions purged"

          # Install Clang-9 and development tools
          apt-get install -y clang-9 libclang-9-dev

          # Set Clang-9 as default compiler
          update-alternatives --install /usr/bin/clang clang /usr/bin/clang-9 100
          update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-9 100
          update-alternatives --install /usr/bin/cc cc /usr/bin/clang-9 100
          update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-9 100

          # Verify installation
          clang --version
          clang++ --version
        if: matrix.config.cc == 'clang'

      - name: Download and extract static LLVM
        run: |
          COMPILER="${{ matrix.config.cc }}"

          # Fetch static clang library built for Ubuntu 20.04
          # Get all releases (including pre-releases) and filter by ubuntu20.04 tag
          releases=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/luckzylp/clangbuild/releases?per_page=100")

          # Find latest release matching criteria
          release_tag=$(echo "$releases" | jq -r \
            'map(select(.tag_name | contains("ubuntu20.04")))
            | sort_by(.published_at) | reverse | .[0].tag_name')

          if [ -z "$release_tag" ] || [ "$release_tag" = "null" ]; then
            echo "::error::No ubuntu20.04 release found"
            exit 1
          fi

          # Use release_tag variable directly instead of step output (fixes invalid reference)
          assets=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/luckzylp/clangbuild/releases/tags/${release_tag}")

          # Find asset URL using regex pattern
          asset_url=$(echo "$assets" | grep -Eo "https://[^\"]*linux-${COMPILER}\.tar\.gz")

          if [ -z "$asset_url" ]; then
            echo "::error::No matching asset found for COMPILER=${COMPILER}"
            exit 1
          fi

          curl -L -o "llvm-static.tar.gz" "$asset_url"
          echo "Downloaded: $(ls -lh llvm-static.tar.gz)"

          mkdir -p "$HOME/llvm-install"
          tar -xzf llvm-static.tar.gz -C "$HOME/llvm-install" --strip-components=1
          echo "LLVM installed at: $HOME/llvm-install"
        shell: bash

      - name: Install libxapian (Linux)
        run: |
          apt update
          apt install -y libxapian-dev

      - name: Install Ghostscript (Linux)
        run: |
          apt update
          apt-get install -y ghostscript

      - name: Install xmllint (Linux)
        run: |
          apt-get update
          apt-get install -y libxml2-utils

      - name: Install Graphviz (Linux)
        run: |
          apt update
          apt-get install -y graphviz

      - name: Install Qt 5
        uses: jurplel/install-qt-action@v3
        with:
          version: 5.*

      - name: Check tool versions (Linux)
        shell: bash
        run: |
          echo "=== perl ===";
          perl --version;
          echo "=== python ===";
          python --version;
          echo "=== cmake ===";
          cmake --version;
          echo "=== latex ===";
          latex --version;
          echo "=== bibtex ===";
          bibtex --version
          echo "=== dvips ===";
          dvips --version
          echo "=== bison ===";
          bison --version;
          echo "=== flex ===";
          flex --version;
          echo "=== dot ===";
          dot -V;
          echo "=== ghostscript ===";
          gs --version;
        if: matrix.config.os != 'windows-latest'

      - name: Configure
        shell: cmake -P {0}
        run: |
          set(ENV{CC} ${{ matrix.config.cc }})
          set(ENV{CXX} ${{ matrix.config.cxx }})

          # Set path to downloaded LLVM
          set(LLVM_PATH "-DCMAKE_PREFIX_PATH=$ENV{HOME}/llvm-install")

          execute_process(
            COMMAND cmake
              -S .
              -B build
              -D CMAKE_BUILD_TYPE=${{ matrix.config.build_type }}
              -G "${{ matrix.config.build_gen }}"
              ${{ matrix.config.cmake_extra_opts }}
              ${LLVM_PATH}
              RESULT_VARIABLE result
          )
          if (NOT result EQUAL 0)
            message(FATAL_ERROR "Bad exit status")
          endif()

      # Build step
      - name: Build
        shell: cmake -P {0}
        run: |
          include(ProcessorCount)
          ProcessorCount(N)
          execute_process(
            COMMAND cmake --build build --parallel ${N}
            RESULT_VARIABLE result
            OUTPUT_VARIABLE output
            ERROR_VARIABLE output
            ECHO_OUTPUT_VARIABLE ECHO_ERROR_VARIABLE
          )
          if (NOT result EQUAL 0)
            string(REGEX MATCH "FAILED:.*$" error_message "${output}")
            string(REPLACE "\n" "%0A" error_message "${error_message}")
            message("::error::${error_message}")
            message(FATAL_ERROR "Build failed")
          endif()

      # Test execution step
      - name: Run tests (Linux)
        shell: cmake -P {0}
        run: |
          set(ENV{CTEST_OUTPUT_ON_FAILURE} "ON")

          execute_process(
            COMMAND
              cmake -E env TEST_FLAGS="--xml --xmlxsd --xhtml --qhp --docbook --rtf --man"
              cmake --build build --target tests
            RESULT_VARIABLE result
          )
          if (NOT result EQUAL 0)
            message(FATAL_ERROR "Running tests failed!")
          endif()
        if: matrix.config.os != 'windows-latest'

      # Generate documentation
      - name: Generate documentation
        shell: cmake -P {0}
        run: |
          execute_process(
            COMMAND cmake --build build --target docs
            RESULT_VARIABLE result
          )
          if (NOT result EQUAL 0)
            message(FATAL_ERROR "Building documentation failed")
          endif()

      # Internal documentation generation (only for primary config)
      - name: Generate Internal documentation
        shell: cmake -P {0}
        run: |
          execute_process(
            COMMAND cmake --build build --target docs_internal
            RESULT_VARIABLE result
          )
          if (NOT result EQUAL 0)
            message(FATAL_ERROR "Building internal documentation failed")
          endif()
        if: matrix.config.name == 'Ubuntu Latest GCC Release x86_64'

      # Artifact preparation with new packaging structure
      - name: Prepare artifacts
        run: |
          # Format version number from release tag
          RELEASE_TAG="${{ needs.get-latest-tag.outputs.release_tag }}"
          VERSION=$(echo "${RELEASE_TAG}" | sed -e 's/Release_//' -e 's/_/./g')
          OS="${{ matrix.config.os }}"
          PLATFORM="${{ matrix.config.platform }}"
          COMPILER="${{ matrix.config.cc }}"
          COMMIT_SHA="${{ needs.get-latest-tag.outputs.commit_sha }}"

          # Create package directory structure
          PACKAGE_DIR="doxygen-${VERSION}"
          mkdir -p "${PACKAGE_DIR}"

          # Download and extract official Linux binaries
          OFFICIAL_URL=$(curl -s "https://api.github.com/repos/doxygen/doxygen/releases/tags/${RELEASE_TAG}" | grep -Eo 'https://[^"]*linux\.bin\.tar\.gz' | head -1)
          wget "${OFFICIAL_URL}" -O doxygen-linux-bin.tar.gz
          mkdir -p official_bin
          tar -xzf doxygen-linux-bin.tar.gz -C official_bin --strip-components=1

          # Create bin directory and copy official binaries
          cp -r official_bin/* "${PACKAGE_DIR}/"
          rm -rf "${PACKAGE_DIR}/bin"
          mkdir -p "${PACKAGE_DIR}/bin"
          cp build/bin/doxy* "${PACKAGE_DIR}/bin/"

          # Create compressed package
          TARBALL="doxygen-${VERSION}.${OS}-${PLATFORM}-${COMPILER}.tar.gz"
          tar -czvf "${TARBALL}" "${PACKAGE_DIR}"

          # Prepare artifacts directory
          mkdir -p artifacts
          mv "${TARBALL}" artifacts/

          # Create build info file
          echo "Doxygen Version: ${VERSION}" > artifacts/build-info.txt
          echo "Build: ${{ matrix.config.name }}" >> artifacts/build-info.txt
          echo "OS: ${{ matrix.config.os }}" >> artifacts/build-info.txt
          echo "Compiler: ${{ matrix.config.cc }}" >> artifacts/build-info.txt
          echo "Build Type: ${{ matrix.config.build_type }}" >> artifacts/build-info.txt
          echo "Commit: $COMMIT_SHA" >> artifacts/build-info.txt
          echo "Build Date: $(date)" >> artifacts/build-info.txt
        shell: bash

      # Upload generated artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.config.name }}
          path: artifacts/*
          retention-days: 1

  # Release creation job
  create-release:
    needs: [get-latest-tag, build]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Fetch doxygen commit
        run: |
          # Fetch the specific commit from doxygen repo
          git fetch https://github.com/doxygen/doxygen.git ${{ needs.get-latest-tag.outputs.commit_sha }} --depth=1

      - name: Install GitHub CLI
        run: sudo apt-get update && sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: all_artifacts
          pattern: artifacts-*
          merge-multiple: true

      - name: Create tag and push
        run: |
          RELEASE_TAG="${{ needs.get-latest-tag.outputs.release_tag }}"
          COMMIT_SHA="${{ needs.get-latest-tag.outputs.commit_sha }}"

          # Clean up possible line breaks
          COMMIT_SHA=$(echo "$COMMIT_SHA" | tr -d '\n')

          # Create tag if doesn't exist
          if ! git rev-parse $RELEASE_TAG >/dev/null 2>&1; then
            echo "Creating tag $RELEASE_TAG pointing to $COMMIT_SHA"
            git tag $RELEASE_TAG $COMMIT_SHA
            git push origin $RELEASE_TAG
          fi

          # Create prerelease targeting specific commit SHA
          if ! gh release view $RELEASE_TAG >/dev/null 2>&1; then
            gh release create "$RELEASE_TAG" \
              --title "Doxygen $RELEASE_TAG" \
              --notes "Automated build from official source" \
              --target "$COMMIT_SHA" \
              --prerelease
          fi

          # Upload all artifacts to release
          find all_artifacts -type f | while read file; do
            gh release upload "$RELEASE_TAG" "$file" --clobber
          done
